### ISSUE TITLE
getting an error when using Song.name

### ISSUE THREAD

**Issue by dashadowofcat** [Bituvo/PyGrounds-API#1]
`Traceback (most recent call last):
  File "c:\Users\USER\Desktop\python nong chooser\main.py", line 3, in <module>
    song = Song(18)
  File "c:\Users\USER\Desktop\python nong chooser\PyGrounds.py", line 79, in __init__     
    self.getSongStats()
  File "c:\Users\USER\Desktop\python nong chooser\PyGrounds.py", line 136, in getSongStats
    del duration[1], duration[2]
IndexError: list assignment index out of range`

thanks in advance!

edit:
the error i was getting happened when i tried using the song chilled 2,
i tried a different id and it works

**Comment by Bituvo** [comment]
this repo is way out of date wtf... i had no idea people were looking at my crusty old repos

tell you what, i'll revive the repo and update it 👍
